database-service:
  spring:
    datasource:
      url: jdbc:mysql://mysql:3306/patientdb?createDatabaseIfNotExist=true
      username: root
      password: Sabrin95@
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
