spring:
  application:
    name: eureka-server  

  config:
<<<<<<< HEAD
    import: optional:configserver:http://config-server:8071
=======
    import: optional:configserver:http://localhost:8888 
>>>>>>> db240ba0d265faaea5ef0b554654590afb87ac77

eureka:
  instance:
    hostname: localhost  
  client:
    register-with-eureka: false  
    fetch-registry: false  
  server:
    wait-time-in-ms-when-sync-empty: 0  

