server:
  port: 8070

spring:
  application:
    name: eureka-server
  config:
    import: "optional:config-server:http://localhost:8071/"

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0

