spring:
  application:
    name: "patient-service"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://mysql:3308/patient_db
    username: root
    password: Sabrin95@
    driver-class-name: com.mysql.cj.jdbc.driver
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:config-server:http://localhost:8071/"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
