spring:
  application:
    name: "web-app"
  profiles:
    active: "prod"
  config:
    import: "optional:config-server:http://localhost:8071"
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8070/eureka/ 

